### ISSUE TITLE
CC license indication for posts

### ISSUE THREAD

**Issue by grussorusso** [hopandfork/hopandfork.github.io#1]
A link to Creative Commons license should be displayed below the post, using following code:
`<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.`

However, we should probably re-organize content which is currently placed below the post (tags, comments, related posts, ...) before adding the CC link.

**Comment by fededido** [comment]
I just checked out some websites, it turns out than on most of them there is something like "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license." on the footer of the webpage, so it is not included in each blog post. We could move the notice to the footer, that is currently quite underpopulated, and leave space on the sidebar for things that need accessibility.

**Comment by grussorusso** [comment]
Good idea! I think this is the best way to solve the issue without wasting
space in the body of the page.

**Comment by grussorusso** [comment]
#fd6517a fixes it.
